import { Link } from 'react-router-dom';
import { StudyInformation } from '@/components/fatigue/debrief/StudyInformation';
export default function PrivacyPage() {
  return <main className="mx-auto max-w-3xl space-y-7 px-5 py-12 leading-relaxed"><Link to="/" className="text-primary">← AeroWake</Link><h1 className="text-3xl font-semibold">Your data in AeroWake</h1>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Roster analysis</h2><p>Guest analyses are held temporarily in server memory for up to one hour and may disappear earlier when capacity is needed. Signed-in uploads, original roster files, and analysis snapshots are saved in your history until you delete the roster or your account.</p></section>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Fatigue reports and drafts</h2><p>Report generation processes the duties, sleep, and narrative you submit and returns a report; it does not save that report in the database. You choose whether to save a draft in this browser tab or download it. Signing out clears the local draft. Submission to your operator is a separate action you control.</p></section>
    <section className="space-y-3"><h2 className="text-lg font-semibold">Optional model study</h2><p>Study participation needs your explicit choice after reading the current information. Signing in or logging a private in-flight rating never joins the study. Earlier automatic participation does not count as consent to this version.</p><StudyInformation className="rounded-xl border border-border bg-card p-4" /></section>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Offline copies and in-flight ratings</h2><p>This browser keeps your last roster for offline use. Signing out clears that roster and synced ratings; unsynced ratings stay bound to the account that recorded them. Guest ratings stay on this device and are not automatically transferred when someone signs in. Delete device ratings from the duty log; choosing to stop contributing and delete entries also clears this account’s ratings on this device.</p></section>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Comparisons</h2><p>Cohort comparisons are optional and use self-declared airline membership. Groups smaller than five are suppressed, but aggregation alone cannot guarantee anonymity. Changing airline or withdrawing consent removes your contribution from published comparisons. Study data is never included.</p></section>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Access, deletion, and retention</h2><p>You can export saved data or delete your account from <Link className="text-primary underline" to="/account">account settings</Link>. Deletion removes active database records and invalidates access. Infrastructure logs and backups have a separate retention policy managed by the service operator. The operator must publish its legal identity, contact, hosting locations, and backup retention before public launch.</p></section>
    <section className="space-y-2"><h2 className="text-lg font-semibold">Use and limitations</h2><p>AeroWake offers model estimates and scoped checks of the supplied records. It has not been independently validated as an operational fitness or compliance determination. Your judgement, operator procedures, and professional assessment take precedence. Confirm parsed times and assumptions before relying on a report.</p></section>
  </main>;
}
