import { KSS_BAND_BOUNDARIES } from '@/lib/risk-scale';

export function MathematicalModelPage() {
  return <article className="mx-auto max-w-3xl space-y-9 px-5 py-10 text-sm leading-7">
    <header className="space-y-3"><p className="eyebrow">Methods and limitations</p><h1 className="text-3xl font-semibold leading-tight">How AeroWake estimates sleepiness</h1><p className="text-muted-foreground">Engine aerowake-4.0-kss · Fatigue report 1.1</p></header>
    <section className="space-y-3"><h2 className="text-xl font-semibold">The prediction</h2><p>AeroWake implements the Three Process Model evaluated by Ingre and colleagues in airline crew (2014, model 5c). The homeostatic process S tracks sleep and wakefulness, the circadian process C follows body-clock phase, and the ultradian process U adds a smaller 12-hour rhythm.</p><p className="rounded border border-border p-4 font-mono">X = S + C + U<br />KSS = 9.68 − 0.46 × X</p><p>Displayed KSS is bounded to 1–9. The legacy index is a linear representation: index = 110 − 10 × KSS. It is not a percentage of cognitive capacity. Workload, cabin hypoxia and time on task are not multipliers of this score.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Observed sleep and predicted sleep</h2><p>Roster analysis infers sleep opportunities from the schedule, location and selected crew rest. Those assumptions are not observations. In a fatigue report, confirmed actual sleep is integrated at its reported duration. Estimated opportunities remain labelled and may receive environment adjustments; reported sleep is not discounted a second time.</p><p>Confirm whether the sleep diary is complete. Missing entries do not prove continuous wakefulness. When coverage is insufficient, the report retains your declaration and withholds an unsupported model assessment.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Reading risk and uncertainty</h2><p>Risk changes at KSS {KSS_BAND_BOUNDARIES.join(', ')}; each exact boundary enters the higher band. A duty's headline uses its peak predicted KSS. Landing KSS is a separate observation in the model timeline.</p><p>The published model's residual error is approximately 1.42 KSS units in its study population. It is not a personal error guarantee. Population percentile estimates are not individual confidence intervals. Sleep deficit is reported as a separate ledger, not silently added to KSS.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Duty and rest checks</h2><p>FDP ends at the last operating arrival; post-flight work remains duty. The basic table requires known crew and acclimatization context. Cumulative checks cover the supplied records, with missing boundary history and unassessed operator approvals shown explicitly. They cannot certify regulatory compliance.</p><p>Times are stored as UTC instants and displayed with the selected zone. Review the import, including overnight flights and any inferred release times, before using the output.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">What has been validated</h2><p>The source research evaluates a model. It does not independently validate AeroWake's parser, inferred sleep, custom reporting rules or complete application. Parser reconciliation and software regression tests check separate engineering properties. Independent scientific and operational review remain necessary before operational use.</p><p>Your own experience, judgement and operator's reporting process take precedence over a model prediction.</p><a className="text-primary underline" href="https://doi.org/10.1371/journal.pone.0108679" target="_blank" rel="noreferrer">Read Ingre et al. (2014)</a></section>
  </article>;
}
