import { Link } from 'react-router-dom';
import { evidenceHref } from '@/data/references';
import { KSS_BAND_BOUNDARIES } from '@/lib/risk-scale';

export function MathematicalModelPage() {
  return <article className="mx-auto max-w-3xl space-y-9 px-5 py-10 text-sm leading-7">
    <header className="space-y-3"><p className="eyebrow">Methods and limitations</p><h1 className="text-3xl font-semibold leading-tight">How Aerowake estimates sleepiness</h1><p className="text-muted-foreground">Engine aerowake-4.2-kss · Fatigue report 1.2</p></header>
    <section className="space-y-3"><h2 className="text-xl font-semibold">The prediction</h2><p>Aerowake implements the Three Process Model evaluated by Ingre and colleagues in airline crew (2014, model 5c). The homeostatic process S tracks sleep and wakefulness, the circadian process C follows body-clock phase, and the ultradian process U adds a smaller 12-hour rhythm.</p><p className="rounded border border-border p-4 font-mono">X = S + C + U<br />KSS = 9.68 − 0.46 × X</p><p>Displayed KSS is bounded to 1–9. The legacy index is a linear representation: index = 110 − 10 × KSS. It is not a percentage of cognitive capacity. Workload, cabin hypoxia and time on task are not multipliers of this score.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Observed sleep and predicted sleep</h2><p>Roster analysis infers sleep opportunities from the schedule, location and selected crew rest. Those assumptions are not observations. In a fatigue report, confirmed actual sleep is integrated at its reported duration. Estimated opportunities remain labelled and may receive environment adjustments; reported sleep is not discounted a second time.</p><p>Confirm whether the sleep diary is complete. Missing entries do not prove continuous wakefulness. When coverage is insufficient, the report retains your declaration and withholds an unsupported model assessment.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Reading risk and uncertainty</h2><p>Risk changes at KSS {KSS_BAND_BOUNDARIES.join(', ')}; each exact boundary enters the higher band. A duty’s headline normally uses the peak predicted KSS from report to the last operating on-blocks. The full duty peak and the prediction at landing are separate values. The displayed value is rounded to one decimal before its band is assigned; a displayed 6.5 is High.</p><p>The published model's residual error is approximately 1.42 KSS units in its study population. It is not a personal error guarantee. Population percentile estimates are not individual confidence intervals. Sleep deficit is reported as a separate ledger, not silently added to KSS.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">Duty and rest checks</h2><p>FDP ends at the last operating arrival; post-flight work remains duty. FDP assessment requires known crew and acclimatization context and a confirmed applicable ruleset. Cumulative checks cover the supplied records, with missing boundary history and unassessed operator approvals shown explicitly. They cannot certify regulatory compliance.</p><p>Times are stored as UTC instants and displayed with the selected zone. Review the import, including overnight flights and any inferred release times, before using the output.</p></section>
    <section className="space-y-3"><h2 className="text-xl font-semibold">What has been validated</h2><p>The source research evaluates a model. It does not independently validate Aerowake's parser, inferred sleep, custom reporting rules or complete application. Parser reconciliation and software regression tests check separate engineering properties. Independent scientific and operational review remain necessary before operational use.</p><p>Sleep inertia, workload, cabin hypoxia and time-on-task multipliers are not included in the current KSS score. The transient period immediately after waking is not modelled. This application has not established equivalence to the Boeing Alertness Model or SAFTE-FAST; their outputs and validation evidence cannot be transferred to Aerowake.</p><p>Your own experience, judgement and operator's reporting process take precedence over a model prediction.</p><Link className="inline-flex min-h-11 items-center text-primary underline" to={evidenceHref('akerstedt_2014')}>Read the source study and its scope</Link></section>
  </article>;
}
