import { useMemo, useState, useCallback, useRef } from 'react';
import { FileText, ArrowLeft, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DutyAnalysis, TimelinePoint } from '@/types/fatigue';
import { computeReportData, type ReportData } from '@/lib/report-narrative';
import { ReportExecutiveSummary } from './ReportExecutiveSummary';
import { ReportDutyProfile } from './ReportDutyProfile';
import { ReportPreDutyState } from './ReportPreDutyState';
import { ReportFatigueTrajectory } from './ReportFatigueTrajectory';
import { ReportCriticalPhases } from './ReportCriticalPhases';
import { ReportRiskAssessment } from './ReportRiskAssessment';
import { ReportMitigations } from './ReportMitigations';
import { ReportRegulatoryContext } from './ReportRegulatoryContext';
import { ReportMethodology } from './ReportMethodology';
import { ReportWhatIfEditor } from './ReportWhatIfEditor';
import { format } from 'date-fns';

interface FatigueReportProps {
  duty: DutyAnalysis;
  analysisId?: string;
  onBack: () => void;
}

/**
 * FatigueReport — professional fatigue assessment report.
 *
 * Renders a full-width, 9-section report with narrative analysis,
 * impairment equivalences, and actionable recommendations.
 * Supports what-if scenario editing and PDF export via browser print.
 */
export function FatigueReport({ duty, analysisId, onBack }: FatigueReportProps) {
  const [whatIfDuty, setWhatIfDuty] = useState<DutyAnalysis | null>(null);
  const [showWhatIf, setShowWhatIf] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  // Use what-if duty if available, otherwise original
  const activeDuty = whatIfDuty ?? duty;
  const timeline = activeDuty.timelinePoints ?? [];

  // Compute all report data
  const reportData = useMemo<ReportData>(
    () => computeReportData(activeDuty, timeline),
    [activeDuty, timeline],
  );

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  const handleWhatIfResult = useCallback((newDuty: DutyAnalysis) => {
    setWhatIfDuty(newDuty);
  }, []);

  const handleResetWhatIf = useCallback(() => {
    setWhatIfDuty(null);
  }, []);

  // Route string for header
  const route = duty.flightSegments && duty.flightSegments.length > 0
    ? duty.flightSegments
        .filter(s => !s.isDeadhead && s.activityCode !== 'IR')
        .map(s => s.departure)
        .concat(duty.flightSegments.filter(s => !s.isDeadhead && s.activityCode !== 'IR').slice(-1).map(s => s.arrival))
        .filter((v, i, a) => a.indexOf(v) === i)
        .join(' – ')
    : '';

  const dateStr = format(duty.date, 'dd MMM yyyy');
  const dayStr = format(duty.date, 'EEEE');

  return (
    <div className="flex flex-col h-full">
      {/* Report toolbar — hidden in print */}
      <div className="print:hidden flex items-center justify-between px-4 py-2 border-b border-border/50 bg-background/80 backdrop-blur-sm flex-shrink-0">
        <Button variant="ghost" size="sm" onClick={onBack} className="gap-1.5">
          <ArrowLeft className="h-4 w-4" />
          Back to Details
        </Button>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowWhatIf(!showWhatIf)}
            className="gap-1.5"
          >
            <FileText className="h-3.5 w-3.5" />
            {showWhatIf ? 'Hide' : 'What-If'}
          </Button>
          <Button variant="default" size="sm" onClick={handlePrint} className="gap-1.5">
            <Printer className="h-3.5 w-3.5" />
            Download PDF
          </Button>
        </div>
      </div>

      {/* Scrollable report content */}
      <div ref={reportRef} className="flex-1 overflow-y-auto">
        <div className="fatigue-report max-w-4xl mx-auto px-6 py-8 space-y-8 print:px-0 print:py-0 print:space-y-6 print:max-w-none">

          {/* ─── Print-only header ─── */}
          <div className="hidden print:block border-b-2 border-black pb-4 mb-6">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-black">FATIGUE ASSESSMENT REPORT</h1>
                <p className="text-sm text-gray-600 mt-1">
                  Generated by Aerowake FRMS — Biomathematical Fatigue Modeling Platform
                </p>
              </div>
              <div className="text-right text-sm text-gray-600">
                <p>{dateStr}</p>
                <p>Report ID: {analysisId ? `${analysisId.slice(0, 8)}` : 'N/A'}</p>
              </div>
            </div>
          </div>

          {/* ─── Screen header ─── */}
          <div className="print:hidden">
            <div className="flex items-center gap-3 mb-1">
              <FileText className="h-5 w-5 text-primary" />
              <h1 className="text-xl font-bold tracking-tight">Fatigue Assessment Report</h1>
            </div>
            <p className="text-sm text-muted-foreground">
              {dayStr}, {dateStr} • {route && <span>{route} • </span>}
              {duty.flightSegments?.filter(s => !s.isDeadhead).map(s => s.flightNumber).join(' / ')}
            </p>
          </div>

          {/* ─── What-If Editor (hidden in print) ─── */}
          {showWhatIf && (
            <div className="print:hidden">
              <ReportWhatIfEditor
                duty={duty}
                analysisId={analysisId}
                onResult={handleWhatIfResult}
                onReset={handleResetWhatIf}
                isModified={whatIfDuty !== null}
              />
            </div>
          )}

          {/* ─── What-if comparison banner ─── */}
          {whatIfDuty && (
            <div className="rounded-lg border border-blue-500/30 bg-blue-500/10 px-4 py-3 print:hidden">
              <p className="text-sm font-medium text-blue-400">
                Showing modified scenario — performance changed from{' '}
                <span className="font-mono">{(duty.minPerformance ?? 0).toFixed(0)}%</span> to{' '}
                <span className="font-mono">{(whatIfDuty.minPerformance ?? 0).toFixed(0)}%</span>
                {' '}({((whatIfDuty.minPerformance ?? 0) - (duty.minPerformance ?? 0) >= 0 ? '+' : '')}{((whatIfDuty.minPerformance ?? 0) - (duty.minPerformance ?? 0)).toFixed(0)}pp)
              </p>
            </div>
          )}

          {/* ─── Report Sections ─── */}
          <div className="report-section">
            <ReportExecutiveSummary data={reportData} />
          </div>

          <div className="report-section">
            <ReportDutyProfile duty={activeDuty} />
          </div>

          <div className="report-section">
            <ReportPreDutyState data={reportData} duty={activeDuty} />
          </div>

          <div className="report-section report-section-break">
            <ReportFatigueTrajectory data={reportData} />
          </div>

          <div className="report-section">
            <ReportCriticalPhases data={reportData} />
          </div>

          <div className="report-section report-section-break">
            <ReportRiskAssessment data={reportData} duty={activeDuty} />
          </div>

          <div className="report-section">
            <ReportMitigations data={reportData} />
          </div>

          <div className="report-section">
            <ReportRegulatoryContext duty={activeDuty} />
          </div>

          <div className="report-section">
            <ReportMethodology />
          </div>

          {/* ─── Print footer ─── */}
          <div className="hidden print:block border-t-2 border-black pt-4 mt-8 text-xs text-gray-500">
            <div className="flex justify-between">
              <p>Aerowake FRMS — Borbely Two-Process Biomathematical Model</p>
              <p>Generated: {new Date().toLocaleDateString('en-GB')} at {new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</p>
            </div>
            <p className="mt-1">
              This report is generated by a biomathematical fatigue model and provides predictions only.
              It does not replace professional medical judgment or regulatory compliance assessment.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
