import { useMemo, useState, useCallback, useRef } from 'react';
import { resolveKss } from '@/lib/risk-scale';
import { FileText, ArrowLeft, Printer } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { DutyAnalysis, TimelinePoint } from '@/types/fatigue';
import { computeReportData, type ReportData } from '@/lib/report-narrative';
import { ReportExecutiveSummary } from './ReportExecutiveSummary';
import { ReportDutyProfile } from './ReportDutyProfile';
import { ReportPreDutyState } from './ReportPreDutyState';
import { ReportFatigueTrajectory } from './ReportFatigueTrajectory';
import { ReportCriticalPhases } from './ReportCriticalPhases';
import { ReportRiskAssessment } from './ReportRiskAssessment';
import { ReportMitigations } from './ReportMitigations';
import { ReportRegulatoryContext } from './ReportRegulatoryContext';
import { ReportMethodology } from './ReportMethodology';
import { ReportWhatIfEditor } from './ReportWhatIfEditor';
import { format } from 'date-fns';

interface FatigueReportProps {
  duty: DutyAnalysis;
  analysisId?: string;
  onBack: () => void;
}

/**
 * FatigueReport — professional fatigue assessment report.
 *
 * Renders a full-width, 9-section report with narrative analysis,
 * impairment equivalences, and actionable recommendations.
 * Supports what-if scenario editing and PDF export via browser print.
 */
export function FatigueReport({ duty, analysisId, onBack }: FatigueReportProps) {
  const [whatIfDuty, setWhatIfDuty] = useState<DutyAnalysis | null>(null);
  const [showWhatIf, setShowWhatIf] = useState(false);
  const reportRef = useRef<HTMLDivElement>(null);

  // Use what-if duty if available, otherwise original
  const activeDuty = whatIfDuty ?? duty;
  const timeline = activeDuty.timelinePoints ?? [];

  // Compute all report data
  const reportData = useMemo<ReportData>(
    () => computeReportData(activeDuty, timeline),
    [activeDuty, timeline],
  );

  const handlePrint = useCallback(() => {
    window.print();
  }, []);

  const handleWhatIfResult = useCallback((newDuty: DutyAnalysis) => {
    setWhatIfDuty(newDuty);
  }, []);

  const handleResetWhatIf = useCallback(() => {
    setWhatIfDuty(null);
  }, []);

  // Route string for header
  const route = activeDuty.flightSegments && activeDuty.flightSegments.length > 0
    ? activeDuty.flightSegments
        .filter(s => !s.isDeadhead && s.activityCode !== 'IR')
        .map(s => s.departure)
        .concat(activeDuty.flightSegments.filter(s => !s.isDeadhead && s.activityCode !== 'IR').slice(-1).map(s => s.arrival))
        .filter((v, i, a) => i === 0 || a[i - 1] !== v)
        .join(' – ')
    : '';

  const dateStr = format(activeDuty.date, 'dd MMM yyyy');
  const dayStr = format(activeDuty.date, 'EEEE');

  return (
    <div className="flex flex-col h-full">
      {/* Report toolbar — hidden in print */}
      <div className="print:hidden flex items-center justify-between px-4 py-2 border-b border-border/50 bg-background/80 backdrop-blur-sm flex-shrink-0">
        <Button variant="ghost" size="sm" onClick={onBack} className="gap-1.5">
          <ArrowLeft className="h-4 w-4" />
          Back to Details
        </Button>
        <div className="flex items-center gap-2">
          <Button
            variant="outline"
            size="sm"
            onClick={() => setShowWhatIf(!showWhatIf)}
            className="gap-1.5"
          >
            <FileText className="h-3.5 w-3.5" />
            {showWhatIf ? 'Hide' : 'What-If'}
          </Button>
          <Button variant="default" size="sm" onClick={handlePrint} className="gap-1.5">
            <Printer className="h-3.5 w-3.5" />
            Print / Save PDF
          </Button>
        </div>
      </div>

      {/* Scrollable report content */}
      <div ref={reportRef} className="flex-1 overflow-y-auto">
        <div className="fatigue-report max-w-4xl mx-auto px-6 py-8 space-y-8 print:px-0 print:py-0 print:space-y-6 print:max-w-none">

          {/* ─── Print-only header ─── */}
          <div className="hidden print:block border-b-2 border-black pb-4 mb-6">
            <div className="flex items-center justify-between">
              <div>
                <h1 className="text-2xl font-bold tracking-tight text-black">FATIGUE ASSESSMENT REPORT</h1>
                <p className="text-sm text-gray-600 mt-1">
                  Generated by AeroWake — experimental fatigue model
                </p>
              </div>
              <div className="text-right text-sm text-gray-600">
                <p>{dateStr}</p>
                <p>{whatIfDuty ? 'Baseline ID (hypothetical scenario)' : 'Report ID'}: {analysisId ? `${analysisId.slice(0, 8)}` : 'N/A'}</p>
              </div>
            </div>
          </div>

          {/* ─── Screen header ─── */}
          <div className="print:hidden">
            <div className="flex items-center gap-3 mb-1">
              <FileText className="h-5 w-5 text-primary" />
              <h1 className="text-xl font-bold tracking-tight">Fatigue Assessment Report</h1>
            </div>
            <p className="text-sm text-muted-foreground">
              {dayStr}, {dateStr} • {route && <span>{route} • </span>}
              {activeDuty.flightSegments?.filter(s => !s.isDeadhead).map(s => s.flightNumber).join(' / ')}
            </p>
          </div>

          {/* ─── What-If Editor (hidden in print) ─── */}
          {showWhatIf && (
            <div className="print:hidden">
              <ReportWhatIfEditor
                duty={duty}
                analysisId={analysisId}
                onResult={handleWhatIfResult}
                onReset={handleResetWhatIf}
                isModified={whatIfDuty !== null}
              />
            </div>
          )}

          {/* ─── What-if comparison banner ─── */}
          {whatIfDuty && (
            <div className="rounded-lg border border-blue-500/30 bg-blue-500/10 px-4 py-3 print:border-black print:bg-white print:text-black">
              <p className="text-sm font-medium text-blue-400">
                HYPOTHETICAL SCENARIO — baseline ID: {analysisId ?? 'unavailable'}. Peak predicted KSS changed from{' '}
                <span className="font-mono">{(resolveKss(duty.maxKss, duty.minPerformance ?? 0) ?? 0).toFixed(1)}</span> to{' '}
                <span className="font-mono">{(resolveKss(whatIfDuty.maxKss, whatIfDuty.minPerformance ?? 0) ?? 0).toFixed(1)}</span>
                {' '}({(() => {
                  const d = (resolveKss(whatIfDuty.maxKss, whatIfDuty.minPerformance ?? 0) ?? 0) - (resolveKss(duty.maxKss, duty.minPerformance ?? 0) ?? 0);
                  return `${d >= 0 ? '+' : ''}${d.toFixed(1)} KSS`;
                })()})
              </p>
            </div>
          )}

          <div className="border-b border-border pb-4 text-sm space-y-1">
            <p><strong>{whatIfDuty ? 'Hypothetical scenario' : 'Roster-based prediction'}</strong> · {activeDuty.modelVersion ?? 'Legacy model version unknown'}</p>
            <p>Review estimated sleep and crew rest before interpreting this report. Values are group-average KSS predictions from the Three Process Model (Ingre et al. 2014; typical error ±1.4 KSS), not a fitness-to-fly determination.</p>
          </div>
          {whatIfDuty?.reportScenario && <div className="text-xs space-y-2">
            <p>Scenario ID: {whatIfDuty.reportScenario.analysisId ?? 'unavailable'} · Baseline ID: {analysisId ?? 'unavailable'}</p>
            <pre className="whitespace-pre-wrap">{JSON.stringify(whatIfDuty.reportScenario.changes, null, 2)}</pre>
          </div>}
          {/* ─── Report Sections ─── */}
          <div className="report-section">
            <ReportExecutiveSummary data={reportData} />
          </div>

          <div className="report-section">
            <ReportDutyProfile duty={activeDuty} />
          </div>

          <div className="report-section">
            <ReportPreDutyState data={reportData} duty={activeDuty} />
          </div>

          <div className="report-section report-section-break">
            <ReportFatigueTrajectory data={reportData} />
          </div>

          <details className="report-appendix space-y-6">
            <summary className="cursor-pointer text-sm font-semibold print:hidden">Technical appendix and supporting details</summary>
          <div className="report-section">
            <ReportCriticalPhases data={reportData} />
          </div>

          <div className="report-section report-section-break">
            <ReportRiskAssessment data={reportData} duty={activeDuty} />
          </div>

          <div className="report-section">
            <ReportMitigations data={reportData} />
          </div>

          <div className="report-section">
            <ReportRegulatoryContext duty={activeDuty} />
          </div>

          <div className="report-section">
            <ReportMethodology />
          </div>

            <pre className="whitespace-pre-wrap text-xs">{JSON.stringify({version: activeDuty.modelVersion ?? 'unknown', thresholds: activeDuty.riskThresholds, parameters: activeDuty.modelParameters}, null, 2)}</pre>
          </details>
          {/* ─── Print footer ─── */}
          <div className="hidden print:block border-t-2 border-black pt-4 mt-8 text-xs text-gray-500">
            <div className="flex justify-between">
              <p>{whatIfDuty ? 'HYPOTHETICAL SCENARIO · ' : ''}AeroWake · {activeDuty.modelVersion ?? 'legacy'}</p>
              <p>Generated: {new Date().toLocaleDateString('en-GB')} at {new Date().toLocaleTimeString('en-GB', { hour: '2-digit', minute: '2-digit' })}</p>
            </div>
            <p className="mt-1">
              This report is generated by a biomathematical fatigue model and provides predictions only.
              It does not replace professional medical judgment or regulatory compliance assessment.
            </p>
          </div>
        </div>
      </div>
    </div>
  );
}
