import { BookOpen } from 'lucide-react';
import { Card, CardContent } from '@/components/ui/card';
import { evidenceHref, getReferenceByKey } from '@/data/references';

export function ReportMethodology() {
  return (
    <section>
      <h2 className="text-sm font-semibold text-muted-foreground uppercase tracking-wider mb-3 print:text-black">
        9. Methodology & References
      </h2>
      <Card variant="glass" className="print:bg-white print:border-gray-300">
        <CardContent className="py-4 px-5 space-y-4">
          <div className="flex items-center gap-2 mb-1">
            <BookOpen className="h-4 w-4 text-primary" />
            <h4 className="text-xs font-medium print:text-black">Biomathematical Fatigue Model</h4>
          </div>

          <p className="text-xs leading-relaxed text-muted-foreground print:text-gray-700">
            This report uses the Three Process Model of alertness (Åkerstedt &amp; Folkard, 1997) in the
            form validated on airline crew by Ingre et al. (2014, model 5c). It predicts sleepiness on the
            Karolinska Sleepiness Scale (KSS, 1–9) from three processes:
          </p>

          <div className="grid grid-cols-1 sm:grid-cols-3 gap-3">
            <ProcessCard
              process="S"
              name="Homeostatic Sleep Pressure"
              description="Builds during wakefulness and recovers during sleep, with a 'brake' that slows recovery near full restoration. This contribution depends on the sleep and wake history supplied."
              reference="Ingre et al., 2014; Åkerstedt & Folkard, 1997"
            />
            <ProcessCard
              process="C"
              name="Circadian Rhythm"
              description="~24h body clock, lowest in the early-morning body-clock hours (WOCL). The implementation assumes adaptation closes about 30% of the remaining time-zone gap per day; this is not a measured rate for the individual pilot."
              reference="Ingre et al., 2014"
            />
            <ProcessCard
              process="U"
              name="Ultradian Rhythm"
              description="A smaller 12-hour component that adds variation within the circadian cycle."
              reference="Ingre et al., 2014"
            />
          </div>

          <p className="text-xs leading-relaxed text-muted-foreground print:text-gray-700">
            Predicted KSS = 9.68 − 0.46·(S + C + U). The 20–100 index shown alongside is a linear
            re-expression (index = 110 − 10·KSS); it is not a percentage and not alcohol-equivalent. Risk
            bands: low KSS &lt; 5.5, moderate 5.5–6.5, high 6.5–7.5, critical 7.5–8.5, extreme ≥ 8.5.
            KSS ≥ 7 is associated with physiological signs of sleepiness (Åkerstedt et al., 2014). The
            90th-percentile KSS and P(KSS ≥ 7) come from the published individual-difference and ordinal
            models. Sleep inertia, time-on-task, workload and cabin hypoxia are not part of the score; the
            7-day sleep deficit is reported separately. Predictions describe a group-average pilot
            and are not a fitness-to-fly determination. The source study reports a residual standard deviation of 1.42 KSS; this is not a personal error bound. The assembled Aerowake product has not been independently validated.
          </p>

          {/* References */}
          <div className="border-t border-border/30 pt-4">
            <h4 className="text-xs font-medium text-muted-foreground mb-2 print:text-gray-600">
              REFERENCES
            </h4>
            <div className="space-y-1.5 text-xs text-muted-foreground print:text-gray-600 leading-relaxed">
              {['akerstedt_2014', 'akerstedt_folkard_1997', 'akerstedt_sleepiness_2014', 'akerstedt_gillberg_1990', 'belenky_2003', 'caldwell_2009', 'icao_9966', 'kamimori_2015', 'ker_2010', 'kitamura_2016', 'rosekind_1994', 'rosekind_1996', 'signal_2013', 'van_dongen_2003'].map(key => <Reference key={key} sourceKey={key} />)}
            </div>
          </div>

          {/* Disclaimer */}
          <div className="border-t border-border/30 pt-3">
            <p className="text-xs text-muted-foreground/70 italic print:text-gray-500">
              Disclaimer: This report is generated by a biomathematical fatigue model and provides
              predictions based on mathematical modeling of human sleep-wake physiology. Predictions
              are estimates and may not reflect the actual fatigue state of any individual pilot.
              Individual differences in sleep need, caffeine sensitivity, and fatigue resistance
              can significantly affect real-world performance. This report does not replace
              professional medical judgment or regulatory compliance assessment.
            </p>
          </div>
        </CardContent>
      </Card>
    </section>
  );
}

function ProcessCard({ process, name, description, reference }: {
  process: string;
  name: string;
  description: string;
  reference: string;
}) {
  const colors: Record<string, string> = {
    S: 'text-red-400 bg-red-400/10 border-red-400/30',
    C: 'text-blue-400 bg-blue-400/10 border-blue-400/30',
    U: 'text-amber-400 bg-amber-400/10 border-amber-400/30',
  };
  const colorClass = colors[process] ?? 'text-primary bg-primary/10 border-primary/30';

  return (
    <div className={`rounded-lg border px-3 py-2.5 ${colorClass} print:bg-gray-50 print:border-gray-200`}>
      <div className="flex items-center gap-2 mb-1">
        <span className="text-sm font-bold font-mono">{process}</span>
        <span className="text-xs font-medium">{name}</span>
      </div>
      <p className="text-xs leading-relaxed opacity-80 print:text-gray-700">{description}</p>
      <p className="text-xs opacity-60 mt-1 print:text-gray-500">{reference}</p>
    </div>
  );
}

function Reference({ sourceKey }: { sourceKey: string }) {
  const source = getReferenceByKey(sourceKey);
  if (!source || source.verification !== 'identified') return null;
  return <p className="pl-4 -indent-4 break-words">{source.full}{' '}
    <a href={source.url} target="_blank" rel="noreferrer" className="text-primary underline print:text-black">{source.doi ? `doi:${source.doi}` : 'Publication'}</a>{' '}
    <a href={evidenceHref(sourceKey)} target="_blank" rel="noreferrer" className="inline-flex min-h-11 items-center text-primary underline print:hidden">Evidence and scope</a>
  </p>;
}
