import { test, expect } from '@playwright/test';
const csv='Date,Flight,Departure,Arrival,STD,STA,Report,Release\n2026-09-05,TEST1,DOH,DMM,23:00,00:15,22:00,03:00\n2026-09-08,TEST2,DOH,FCO,08:00,13:00,07:00,15:00\n';

test('guest import review, map recovery, report draft, print and navigation',async({page},testInfo)=>{
  const errors: string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  let airportOffline=true;
  let previewUnavailable=true;
  await page.route('**/api/roster/preview',route=>previewUnavailable ? route.fulfill({status:404,contentType:'application/json',body:'{"detail":"Not Found"}'}) : route.continue());
  await page.route('**/api/airports/batch**',route=>airportOffline ? route.fulfill({status:503,contentType:'application/json',body:'{"detail":"test offline"}'}) : route.continue());
  await page.goto('/');
  await page.getByRole('button',{name:'Analyse a roster',exact:true}).click();
  await expect(page).toHaveURL(/\/roster$/);
  await expect(page.getByRole('heading',{name:'Check your roster',exact:true})).toBeVisible();
  await page.evaluate(()=>window.scrollTo(0,0));
  await page.screenshot({path:testInfo.outputPath('roster-upload.png'),fullPage:true});
  // The roster is read on selection; no base is typed first.
  await page.getByLabel('Choose roster file (PDF or CSV)').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
  await expect(page.getByRole('alert')).toContainText('Roster import is temporarily unavailable.');
  await expect(page.getByRole('button',{name:'Analyse roster',exact:true})).toHaveCount(0);
  previewUnavailable=false;
  await page.getByRole('button',{name:'Try again',exact:true}).click();
  // Half the duty ends are away from DOH, so the CSV base is asked for rather than guessed.
  await page.getByLabel('Home base',{exact:true}).fill('DOH');
  await page.getByRole('button',{name:'Continue',exact:true}).click();
  await expect(page.getByRole('heading',{name:'September 2026 roster'})).toBeFocused();
  await expect(page.getByText('Entered by you',{exact:true})).toBeVisible();
  await page.getByRole('button',{name:'Analyse roster',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your fatigue outlook'})).toBeVisible();
  await expect(page.getByRole('region',{name:'Roster calendar',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Navigation',exact:true})).toBeVisible();
  await page.getByRole('dialog',{name:'Navigation',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('tab',{name:'Calendar',exact:true}).click();
  // The interactive calendar has its own visible view, on desktop and mobile.
  const calendar=page.getByRole('region',{name:'Roster calendar',exact:true});
  await expect(calendar.getByRole('heading',{name:'Roster calendar',exact:true})).toBeVisible();
  await expect(calendar.getByRole('tab',{name:'Home base',exact:true})).toHaveAttribute('aria-selected','true');
  await expect(page.getByText('Analysis complete!',{exact:true})).toBeHidden();
  await page.evaluate(()=>window.scrollTo(0,0));
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('roster-calendar.png'),fullPage:true});
  await expect(page.getByRole('heading',{name:'Your fatigue outlook'})).toBeHidden();
  const dutyResponse=page.waitForResponse(r=>r.url().includes('/api/duty/') && r.request().method()==='GET');
  await calendar.getByRole('button',{name:'Open duty on Sat 5 Sep: TEST1',exact:true}).click();
  expect((await dutyResponse).status()).toBe(200);
  const dutyDialog=page.getByRole('dialog',{name:'Duty details, Sat 5 Sep 2026',exact:true});
  await expect(dutyDialog).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('duty-details.png')});
  await dutyDialog.getByRole('button',{name:'Close',exact:true}).click();
  await calendar.getByRole('tab',{name:'UTC',exact:true}).click();
  await expect(calendar.getByRole('tab',{name:'UTC',exact:true})).toHaveAttribute('aria-selected','true');
  await calendar.getByRole('button',{name:'Open duty on Tue 8 Sep: TEST2',exact:true}).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog',{name:'Duty details, Tue 8 Sep 2026',exact:true})).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await calendar.getByRole('tab',{name:'Home base',exact:true}).click();
  const sleep=calendar.getByRole('button',{name:/^Inspect estimated sleep/}).first();
  await sleep.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByText('Estimated sleep from the roster, not a record of sleep taken.',{exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  await calendar.getByRole('button',{name:/^FDP limit for/}).first().click();
  await expect(page.getByRole('dialog',{name:/^Duty details/})).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('tab',{name:'Sleep & recovery',exact:true}).click();
  await expect(page.getByLabel('Predicted sleepiness through the month')).toBeVisible();
  await page.evaluate(()=>window.scrollTo(0,0));
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.screenshot({path:testInfo.outputPath('roster-recovery.png'),fullPage:true});
  await expect(calendar).toBeHidden();
  await page.getByRole('tab',{name:'FTL checks',exact:true}).click();
  await expect(page.getByRole('heading',{name:'FTL checks',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Routes',exact:true}).click();
  await expect(page.getByRole('button',{name:'Retry map'})).toBeVisible();
  airportOffline=false;
  await page.getByRole('button',{name:'Retry map'}).click();
  await expect(page.getByRole('button',{name:'Retry map'})).toHaveCount(0);
  await page.getByRole('button',{name:'Map',exact:true}).click();
  await expect(page.locator('svg[data-mode="flat"]')).toBeVisible();
  await page.getByRole('button',{name:'List',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('tab',{name:'Outlook',exact:true}).click();
  // No duty reaches the default watch level in this roster, so report from the navigation.
  await page.getByRole('navigation',{name:'Sections'}).getByRole('button',{name:'Report fatigue',exact:true}).click();
  await expect(page).toHaveURL(/\/report$/);
  await page.getByLabel(/Keep a draft in this browser tab/).check();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByLabel(/This diary includes every sleep and nap in the period/).check();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('radio',{name:/8 Sleepy, some effort/}).check();
  await page.getByRole('button',{name:'Generate report',exact:true}).click();
  await expect(page.getByRole('button',{name:'Download PDF'})).toBeVisible();
  await expect(page.getByRole('region',{name:'Key facts'})).toBeVisible();
  await expect(page.getByRole('region',{name:'Send to your operator'})).toBeVisible();
  await expect(page.getByRole('heading',{name:/^Figure 1. Sleep, duty and event/})).toBeVisible();
  await page.emulateMedia({media:'print'});
  await expect(page.getByRole('heading',{name:'Supporting detail'})).toBeVisible();
  await expect(page.locator('#fatigue-report-print .report-appendix')).toHaveCSS('break-before','page');
  // Printed headings stay near-black ink.
  const h1Color=await page.locator('#fatigue-report-print h1').evaluate(el=>getComputedStyle(el).color);
  expect(h1Color.match(/\d+/g)!.slice(0,3).every(v=>Number(v)<=60)).toBe(true);
  await page.emulateMedia({media:'screen'});
  await page.getByRole('button',{name:'Edit inputs'}).click();
  await page.reload();
  await expect(page.getByLabel(/Keep a draft in this browser tab/)).toBeChecked();
  await page.goto('/learn');
  await expect(page.getByRole('tab',{name:'How the model works'})).toBeVisible();
  await page.getByRole('tab',{name:'How the model works'}).click();
  await expect(page.getByRole('heading',{name:'How AeroWake estimates sleepiness'})).toBeVisible();
  await page.goBack();
  await expect(page).toHaveURL(/\/report$/);
  await expect(page.getByLabel(/Keep a draft in this browser tab/)).toBeChecked();
  expect(errors).toEqual([]);
});
