import { test, expect } from '@playwright/test';
const csv='Date,Flight,Departure,Arrival,STD,STA,Report,Release\n2026-09-05,TEST1,DOH,DMM,23:00,00:15,22:00,03:00\n2026-09-08,TEST2,DOH,FCO,08:00,13:00,07:00,15:00\n';

test('guest import review, map recovery, report draft, print and navigation',async({page})=>{
  const errors: string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  let airportOffline=true;
  let previewUnavailable=true;
  await page.route('**/api/roster/preview',route=>previewUnavailable ? route.fulfill({status:404,contentType:'application/json',body:'{"detail":"Not Found"}'}) : route.continue());
  await page.route('**/api/airports/batch**',route=>airportOffline ? route.fulfill({status:503,contentType:'application/json',body:'{"detail":"test offline"}'}) : route.continue());
  await page.goto('/');
  await page.getByRole('button',{name:'Analyse a roster',exact:true}).click();
  await expect(page).toHaveURL(/\/roster$/);
  await page.getByLabel('Home base (IATA)').fill('DOH');
  await page.getByLabel('Choose roster file (PDF or CSV)').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
  await page.getByRole('button',{name:'Review roster',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Roster import is temporarily unavailable.');
  await expect(page.getByRole('button',{name:'Run analysis',exact:true})).toHaveCount(0);
  previewUnavailable=false;
  await page.getByRole('button',{name:'Review roster',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Review the import'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Run analysis',exact:true})).toBeDisabled();
  await page.getByLabel('I have reviewed the dates, time zones, and assumptions. Continue with these inputs.').check();
  await page.getByRole('button',{name:'Run analysis',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Duties to watch',exact:true})).toBeVisible();
  await expect(page.getByRole('button',{name:'Retry map'})).toBeVisible();
  airportOffline=false;
  await page.getByRole('button',{name:'Retry map'}).click();
  await expect(page.getByRole('button',{name:'Retry map'})).toHaveCount(0);
  await page.getByRole('button',{name:'Flat routes',exact:true}).click();
  await page.getByRole('button',{name:'list',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('button',{name:/Report fatigue for duty/}).first().click();
  await expect(page).toHaveURL(/\/report$/);
  await page.getByLabel(/Save this draft in this browser tab/).check();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByLabel(/I have entered every sleep period and nap/).check();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('radio',{name:/8 Sleepy, some effort/}).check();
  await expect(page.getByRole('button',{name:'Generate report',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Use the fatigue event time'}).click();
  await page.getByRole('button',{name:'Generate report',exact:true}).click();
  await expect(page.getByRole('button',{name:'Print / PDF'})).toBeVisible();
  await expect(page.getByLabel('Evidence coverage')).toBeVisible();
  await expect(page.getByLabel('Submission summary')).toBeVisible();
  await expect(page.getByRole('heading',{name:'Predicted sleepiness across the period'})).toBeVisible();
  await page.emulateMedia({media:'print'});
  await expect(page.getByRole('heading',{name:'Supporting detail'})).toBeVisible();
  await expect(page.locator('#fatigue-report-print .report-appendix')).toHaveCSS('break-before','page');
  await expect(page.locator('#fatigue-report-print h1')).toHaveCSS('color','rgb(17, 17, 17)');
  await page.emulateMedia({media:'screen'});
  await page.getByRole('button',{name:'Edit inputs'}).click();
  await page.reload();
  await expect(page.getByLabel(/Save this draft in this browser tab/)).toBeChecked();
  await page.goto('/learn');
  await expect(page.getByRole('tab',{name:'How the model works'})).toBeVisible();
  await page.getByRole('tab',{name:'How the model works'}).click();
  await expect(page.getByRole('heading',{name:'How AeroWake estimates sleepiness'})).toBeVisible();
  await page.goBack();
  await expect(page).toHaveURL(/\/report$/);
  await expect(page.getByLabel(/Save this draft in this browser tab/)).toBeChecked();
  expect(errors).toEqual([]);
});
