import { test, expect } from '@playwright/test';
const csv='Date,Flight,Departure,Arrival,STD,STA,Report,Release\n2026-09-05,TEST1,DOH,DMM,23:00,00:15,22:00,03:00\n2026-09-08,TEST2,DOH,FCO,08:00,13:00,07:00,15:00\n';

test('guest import review, map recovery, report draft, print and navigation',async({page},testInfo)=>{
  const errors: string[]=[]; page.on('pageerror',e=>errors.push(e.message));
  let airportOffline=true;
  let previewUnavailable=true;
  await page.route('**/api/roster/preview',route=>previewUnavailable ? route.fulfill({status:404,contentType:'application/json',body:'{"detail":"Not Found"}'}) : route.continue());
  await page.route('**/api/airports/batch**',route=>airportOffline ? route.fulfill({status:503,contentType:'application/json',body:'{"detail":"test offline"}'}) : route.continue());
  await page.goto('/');
  await page.getByRole('button',{name:'Analyse a roster',exact:true}).click();
  await expect(page).toHaveURL(/\/roster$/);
  await page.getByLabel('Home base (IATA)').fill('DOH');
  await page.getByLabel('Choose roster file (PDF or CSV)').setInputFiles({name:'synthetic.csv',mimeType:'text/csv',buffer:Buffer.from(csv)});
  await page.getByRole('button',{name:'Review roster',exact:true}).click();
  await expect(page.getByRole('alert')).toContainText('Roster import is temporarily unavailable.');
  await expect(page.getByRole('button',{name:'Run analysis',exact:true})).toHaveCount(0);
  previewUnavailable=false;
  await page.getByRole('button',{name:'Review roster',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Review the import'})).toBeVisible();
  await expect(page.getByRole('button',{name:'Run analysis',exact:true})).toBeDisabled();
  await page.getByLabel('I have reviewed the dates, time zones, and assumptions. Continue with these inputs.').check();
  await page.getByRole('button',{name:'Run analysis',exact:true}).click();
  await expect(page.getByRole('heading',{name:'Your fatigue outlook'})).toBeVisible();
  await expect(page.getByRole('region',{name:'Roster calendar',exact:true})).toHaveCount(0);
  await page.getByRole('button',{name:'Open navigation',exact:true}).click();
  await expect(page.getByRole('dialog',{name:'Navigation',exact:true})).toBeVisible();
  await page.getByRole('dialog',{name:'Navigation',exact:true}).getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('tab',{name:'Calendar',exact:true}).click();
  // The interactive calendar has its own visible view, on desktop and mobile.
  const calendar=page.getByRole('region',{name:'Roster calendar',exact:true});
  await expect(calendar.getByRole('heading',{name:'Roster calendar',exact:true})).toBeVisible();
  await expect(calendar.getByRole('tab',{name:'Home base',exact:true})).toHaveAttribute('aria-selected','true');
  await page.screenshot({path:testInfo.outputPath('roster-calendar.png'),fullPage:true});
  await expect(page.getByRole('heading',{name:'Your fatigue outlook'})).toBeHidden();
  const dutyResponse=page.waitForResponse(r=>r.url().includes('/api/duty/') && r.request().method()==='GET');
  await calendar.getByRole('button',{name:'Open duty on Sat 5 Sep: TEST1',exact:true}).click();
  expect((await dutyResponse).status()).toBe(200);
  const dutyDialog=page.getByRole('dialog',{name:'Duty Details — Sep 05, 2026',exact:true});
  await expect(dutyDialog).toBeVisible();
  await dutyDialog.getByRole('button',{name:'Close',exact:true}).click();
  await calendar.getByRole('tab',{name:'UTC',exact:true}).click();
  await expect(calendar.getByRole('tab',{name:'UTC',exact:true})).toHaveAttribute('aria-selected','true');
  await calendar.getByRole('button',{name:'Open duty on Tue 8 Sep: TEST2',exact:true}).focus();
  await page.keyboard.press('Enter');
  await expect(page.getByRole('dialog',{name:'Duty Details — Sep 08, 2026',exact:true})).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await calendar.getByRole('tab',{name:'Home base',exact:true}).click();
  const sleep=calendar.getByRole('button',{name:/^Inspect estimated sleep/}).first();
  await sleep.focus();
  await page.keyboard.press('Enter');
  await expect(page.getByText('Estimated sleep from the roster, not a record of sleep taken.',{exact:true})).toBeVisible();
  await page.keyboard.press('Escape');
  await calendar.getByRole('button',{name:/^FDP limit for/}).first().click();
  await expect(page.getByRole('dialog',{name:/^Duty Details/})).toBeVisible();
  await page.getByRole('dialog').getByRole('button',{name:'Close',exact:true}).click();
  await page.getByRole('tab',{name:'Sleep & recovery',exact:true}).click();
  await expect(page.getByLabel('Predicted sleepiness through the month')).toBeVisible();
  await page.screenshot({path:testInfo.outputPath('roster-recovery.png'),fullPage:true});
  await expect(calendar).toBeHidden();
  await page.getByRole('tab',{name:'FTL checks',exact:true}).click();
  await expect(page.getByRole('heading',{name:'EASA flight-time limitations',exact:true})).toBeVisible();
  await page.getByRole('tab',{name:'Routes',exact:true}).click();
  await expect(page.getByRole('button',{name:'Retry map'})).toBeVisible();
  airportOffline=false;
  await page.getByRole('button',{name:'Retry map'}).click();
  await expect(page.getByRole('button',{name:'Retry map'})).toHaveCount(0);
  await page.getByRole('button',{name:'Flat routes',exact:true}).click();
  await page.getByRole('button',{name:'list',exact:true}).click();
  expect(await page.evaluate(()=>document.documentElement.scrollWidth<=innerWidth)).toBe(true);
  await page.getByRole('tab',{name:'Outlook',exact:true}).click();
  await page.getByRole('button',{name:/Report fatigue for duty/}).first().click();
  await expect(page).toHaveURL(/\/report$/);
  await page.getByLabel(/Save this draft in this browser tab/).check();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByLabel(/I have entered every sleep period and nap/).check();
  await page.getByRole('button',{name:'Next',exact:true}).click();
  await page.getByRole('radio',{name:/8 Sleepy, some effort/}).check();
  await expect(page.getByRole('button',{name:'Generate report',exact:true})).toBeDisabled();
  await page.getByRole('button',{name:'Use the fatigue event time'}).click();
  await page.getByRole('button',{name:'Generate report',exact:true}).click();
  await expect(page.getByRole('button',{name:'Print / PDF'})).toBeVisible();
  await expect(page.getByLabel('Evidence coverage')).toBeVisible();
  await expect(page.getByLabel('Submission summary')).toBeVisible();
  await expect(page.getByRole('heading',{name:'Predicted sleepiness across the period'})).toBeVisible();
  await page.emulateMedia({media:'print'});
  await expect(page.getByRole('heading',{name:'Supporting detail'})).toBeVisible();
  await expect(page.locator('#fatigue-report-print .report-appendix')).toHaveCSS('break-before','page');
  await expect(page.locator('#fatigue-report-print h1')).toHaveCSS('color','rgb(17, 17, 17)');
  await page.emulateMedia({media:'screen'});
  await page.getByRole('button',{name:'Edit inputs'}).click();
  await page.reload();
  await expect(page.getByLabel(/Save this draft in this browser tab/)).toBeChecked();
  await page.goto('/learn');
  await expect(page.getByRole('tab',{name:'How the model works'})).toBeVisible();
  await page.getByRole('tab',{name:'How the model works'}).click();
  await expect(page.getByRole('heading',{name:'How AeroWake estimates sleepiness'})).toBeVisible();
  await page.goBack();
  await expect(page).toHaveURL(/\/report$/);
  await expect(page.getByLabel(/Save this draft in this browser tab/)).toBeChecked();
  expect(errors).toEqual([]);
});
