import { test, expect } from '@playwright/test';

const csv = 'Date,Flight,Departure,Arrival,STD,STA,Report,Release\n2026-09-05,TEST1,DOH,DMM,23:00,00:15,22:00,03:00\n2026-09-08,TEST2,DOH,FCO,08:00,13:00,07:00,15:00\n';

test('pilot outlook becomes a prospective concern with traceable evidence', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/');
  await page.getByRole('button', { name: 'Analyse a roster', exact: true }).click();
  await page.getByLabel('Home base (IATA)').fill('DOH');
  await page.getByLabel('Choose roster file (PDF or CSV)').setInputFiles({ name: 'synthetic-outlook.csv', mimeType: 'text/csv', buffer: Buffer.from(csv) });
  await page.getByRole('button', { name: 'Review roster', exact: true }).click();
  await page.getByLabel('I have reviewed the dates, time zones, and assumptions. Continue with these inputs.').check();
  await page.getByRole('button', { name: 'Run analysis', exact: true }).click();
  await expect(page.getByRole('heading', { name: 'Your fatigue outlook' })).toBeVisible();
  const modelWatchCount = await page.getByTestId('duty-watch-card').count();
  await page.getByLabel('My watch level (KSS)').selectOption('9');
  await expect(page.getByTestId('duty-watch-card')).toHaveCount(modelWatchCount);
  await page.getByLabel('My watch level (KSS)').selectOption('6');
  await expect(page.getByText('Analysis complete!', { exact: true })).toBeHidden();
  await page.evaluate(() => window.scrollTo(0, 0));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('pilot-outlook.png'), fullPage: true });
  await page.getByRole('button', { name: 'Switch to dark theme', exact: true }).click();
  await expect(page.locator('html')).toHaveClass(/dark/);
  await page.screenshot({ path: testInfo.outputPath('pilot-outlook-dark.png'), fullPage: true });
  await page.getByRole('button', { name: 'Switch to light theme', exact: true }).click();
  await expect(page.locator('html')).toHaveClass(/light/);
  await page.getByRole('tab', { name: 'Sleep & recovery', exact: true }).click();
  await page.getByRole('button', { name: /^Raise roster concern for/ }).last().click();
  await expect(page.getByRole('heading', { name: 'Raise a roster concern' })).toBeVisible();
  await expect(page.getByLabel('Personal watch reference (KSS)')).toHaveValue('6');
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Mark as actual sleep', exact: true }).first().click();
  await expect(page.getByText('Reported', { exact: true })).toHaveCount(1);
  await page.getByLabel(/I have reviewed all sleep windows in this scenario/).check();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByLabel('Your account').fill('I have experienced difficulty recovering between similar duties. Please review the proposed sequence.');
  const responsePromise = page.waitForResponse(r => r.url().endsWith('/api/fatigue-report') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Generate report', exact: true }).click();
  const response = await responsePromise;
  expect(response.status(), await response.text()).toBe(200);
  const report = await response.json();
  expect(report.event.type).toBe('roster_concern');
  expect(report.self_assessment).toBeNull();
  expect(report.watch_reference.kss).toBe(6);
  expect(report.duties.every((d: { status: string }) => d.status === 'planned')).toBe(true);
  expect(report.data_quality.reported_sleeps).toBe(1);
  expect(report.data_quality.estimated_sleeps).toBeGreaterThan(0);
  expect(report.data_quality.model_available).toBe(true);
  expect(report.scientific_basis.length).toBeGreaterThan(0);
  await expect(page.getByLabel('Three sources of evidence')).toBeVisible();
  await expect(page.getByText('Prospective roster concern', { exact: true })).toBeVisible();
  await page.evaluate(() => window.scrollTo(0, 0));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('pilot-concern.png'), fullPage: true });
  if (testInfo.project.name === 'desktop') await page.pdf({ path: testInfo.outputPath('pilot-concern.pdf'), format: 'A4', preferCSSPageSize: true, printBackground: true });
  expect(errors).toEqual([]);
});
