import { test, expect } from '@playwright/test';

test('manual recent days produce a reviewable SMS export without a roster', async ({ page }, testInfo) => {
  const errors: string[] = [];
  page.on('pageerror', error => errors.push(error.message));
  await page.goto('/report');
  await expect(page.locator('html')).toHaveClass(/light/);
  await page.getByLabel('Home base (IATA)').fill('LGW');
  await expect(page.getByText('Time zone: Europe/London', { exact: true })).toBeVisible();
  await page.getByRole('button', { name: 'UTC', exact: true }).click();
  await page.getByLabel('When did you call / feel fatigued?').fill('2026-09-09T08:00');
  await page.getByLabel('What happened?').selectOption('fatigue_after_duty');
  await page.getByRole('button', { name: '3 days before event' }).click();
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByRole('button', { name: 'Review Mon 7 Sept' }).click();
  await page.getByRole('button', { name: 'Add duty', exact: true }).click();
  await expect(page.getByLabel('Report', { exact: true })).toHaveValue('2026-09-07T08:00');
  await page.getByLabel('Activity').selectOption('ground');
  await page.getByLabel('Status', { exact: true }).selectOption('operated');
  await page.getByRole('button', { name: 'Review Tue 8 Sept' }).click();
  await page.getByRole('button', { name: 'Add duty', exact: true }).click();
  await page.getByLabel('Report', { exact: true }).fill('2026-09-08T22:00');
  await expect(page.getByRole('button', { name: 'Next', exact: true })).toBeDisabled();
  await page.getByLabel('Release (off duty)').fill('2026-09-09T06:00');
  await page.getByLabel('Activity').selectOption('ground');
  await page.getByLabel('Status', { exact: true }).selectOption('operated');
  await page.getByRole('radio', { name: 'Duty affected by fatigue' }).check();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('daybook-duties.png'), fullPage: true });
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  for (const day of ['Mon 7 Sept', 'Tue 8 Sept']) {
    await page.getByRole('button', { name: `Review ${day}` }).click();
    await page.getByRole('button', { name: 'Last night’s sleep', exact: true }).click();
    await page.getByRole('button', { name: 'Mark as actual sleep', exact: true }).click();
  }
  await page.getByRole('button', { name: 'Review Tue 8 Sept' }).click();
  await page.getByRole('button', { name: 'Nap', exact: true }).click();
  await page.getByRole('button', { name: 'Mark as actual sleep', exact: true }).click();
  await expect(page.getByLabel('Sleep before the event')).toContainText('1h 00m');
  await expect(page.getByLabel('Sleep before the event')).toContainText('9h 00m');
  await page.getByLabel(/I have entered every sleep period and nap/).check();
  // A correction invalidates the completeness acknowledgement until reviewed again.
  await page.getByLabel('Quality').first().selectOption('2');
  await expect(page.getByLabel(/I have entered every sleep period and nap/)).not.toBeChecked();
  await page.getByLabel(/I have entered every sleep period and nap/).check();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('daybook-sleep.png'), fullPage: true });
  await page.getByRole('button', { name: 'Next', exact: true }).click();
  await page.getByLabel('Your account').fill('After the overnight duty I struggled to concentrate. I took a short nap before the duty, but my recovery felt insufficient. I informed the duty manager.');
  const responsePromise = page.waitForResponse(r => r.url().endsWith('/api/fatigue-report') && r.request().method() === 'POST');
  await page.getByRole('button', { name: 'Generate report', exact: true }).click();
  const response = await responsePromise;
  expect(response.status(), await response.text()).toBe(200);
  const report = await response.json();
  expect(report.duties).toHaveLength(2);
  expect(report.duties.every((duty: { status: string }) => duty.status === 'operated')).toBe(true);
  expect(report.data_quality.reported_sleeps).toBe(3);
  expect(report.data_quality.estimated_sleeps).toBe(0);
  await expect(page.getByLabel('Export to your SMS')).toBeVisible();
  await page.getByRole('button', { name: 'Preview submission text' }).click();
  const submission = page.getByLabel('Submission text', { exact: true });
  expect(await submission.inputValue()).toContain('I informed the duty manager.');
  expect(await submission.inputValue()).toContain('Duty history');
  expect(await submission.inputValue()).toContain('Sleep history');
  expect(await submission.inputValue()).toContain('Model context');
  expect(await submission.inputValue()).toContain('Evidence and limitations');
  await page.evaluate(() => { Object.defineProperty(navigator, 'clipboard', { configurable: true, value: { writeText: async () => { throw new Error('Blocked for test'); } } }); });
  await page.getByRole('button', { name: 'Copy for SMS' }).click();
  await expect(page.getByRole('alert')).toContainText('Your browser blocked copying.');
  const downloadPromise = page.waitForEvent('download');
  await page.getByRole('button', { name: 'Download text', exact: true }).click();
  expect((await downloadPromise).suggestedFilename()).toBe('fatigue-report-2026-09-09.txt');
  await page.getByRole('button', { name: 'Hide submission text' }).click();
  await page.evaluate(() => window.scrollTo(0, 0));
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.screenshot({ path: testInfo.outputPath('sms-report.png'), fullPage: true });
  if (testInfo.project.name === 'desktop') await page.pdf({ path: testInfo.outputPath('sms-report.pdf'), format: 'A4', preferCSSPageSize: true, printBackground: true });
  expect(errors).toEqual([]);
});

test('daylight landing stays readable with a saved dark workspace preference', async ({ page }, testInfo) => {
  await page.addInitScript(() => localStorage.setItem('fatigue-theme', 'dark'));
  await page.goto('/');
  await expect(page.getByRole('heading', { name: /Understand your roster/ })).toBeVisible();
  await expect(page.locator('.landing-daylight')).toHaveCSS('background-color', 'rgb(248, 251, 253)');
  // Scroll reveals are captured in their visible state, including reduced motion.
  await page.getByRole('button', { name: 'Explore the workflow' }).click();
  await page.getByRole('heading', { name: 'Keep a clear record' }).scrollIntoViewIfNeeded();
  await page.evaluate(() => window.scrollTo(0, 0));
  await page.screenshot({ path: testInfo.outputPath('landing-daylight.png'), fullPage: true });
  expect(await page.evaluate(() => document.documentElement.scrollWidth <= innerWidth)).toBe(true);
  await page.getByRole('link', { name: 'Create a fatigue report', exact: true }).click();
  await expect(page).toHaveURL(/\/report$/);
  await expect(page.locator('html')).toHaveClass(/dark/);
});
